### ISSUE TITLE
RuntimeError for training on hippocampus dataset

### ISSUE THREAD

**Issue by noushinha** [VinAIResearch/3D-UCaps#1]
For the ucaps model and task04_hippocampus, The following error is thrown:

"RuntimeError: Given groups=1, weight of size [16, 2, 5, 5, 5], expected input[1, 1, 32, 32, 32] to have 2 channels, but got 1 channels instead"

I did not change any part of the code yet. Just the root_dir is set to a custom path and dataset to "task04_hippocampus".
Any help is much appreciated.

**Comment by cndu234** [comment]
@noushinha any comments on this issues? [https://github.com/VinAIResearch/3D-UCaps/issues/4#issue-1057667400](url) and [https://github.com/VinAIResearch/3D-UCaps/issues/3#issue-1057044617](url). 
Please help me if you have encountered these issues
