### ISSUE TITLE
 a dimension parameter in Convolution

### ISSUE THREAD

**Issue by code-aifarmer** [VinAIResearch/3D-UCaps#11]
![image](https://user-images.githubusercontent.com/73326606/222939058-1f54833c-7eba-469f-abdb-f4b6bd5f9448.png)
Hello, your project is excellent. I want to know why there is a dimension parameter in Convolution, and an error occurred here when I was running

**Comment by hoangtan96dl** [comment]
Ref link to that class is here: https://docs.monai.io/en/stable/networks.html#convolution
Looks like they have change the name of that argument to `spatial_dims` in newer version. I used MONAI version 0.6 at that time hence you can install that version if you do not want to change the code

**Comment by code-aifarmer** [comment]
> Ref link to that class is here: https://docs.monai.io/en/stable/networks.html#convolution Looks like they have change the name of that argument to `spatial_dims` in newer version. I used MONAI version 0.6 at that time hence you can install that version if you do not want to change the code

Thanks for your reply!
